name: SmartHealth
options:
    deploymentTarget:
        iOS: 14.0
targets:
    SmartHealth:
        type: application
        platform: iOS
        sources: [App, Models, Services, Views]
        settings:
            PRODUCT_BUNDLE_IDENTIFIER: com.salvatore.smarthealthdev
            INFOPLIST_FILE: SmartHealth/Info.plist
            IPHONEOS_DEPLOYMENT_TARGET: "14.0"
info:
    path: SmartHealth/Info.plist
