name: SmartHealth
options:
    deploymentTarget:
        iOS: 15.0
targets:
    SmartHealth:
        type: application
        platform: iOS
        sources: [App, Models, Services, Views]
        settings:
            PRODUCT_BUNDLE_IDENTIFIER: com.elperrix.smarthealth
            INFOPLIST_FILE: SmartHealth/Info.plist
            IPHONEOS_DEPLOYMENT_TARGET: "15.0"
info:
    path: SmartHealth/Info.plist
                UIInterfaceOrientationPortrait: true
            UIInterfaceOrientationLandscapeLeft: true
            UIInterfaceOrientationLandscapeRight: true
            UIInterfaceOrientationPortraitUpsideDown: false
            UILaunchStoryboardName: LaunchScreen
